#### Import Table

In [1]:
import pandas as pd
import numpy as np

#### Load the tables

In [2]:
df_campaign  = pd.read_csv("C:/Users/OlusegunAdesanya/Downloads/campaign_data.csv")
df_affmatrix = pd.read_csv("C:/Users/OlusegunAdesanya/Downloads/affMatrix_feed.csv")
df_trackaff = pd.read_csv("C:/Users/OlusegunAdesanya/Downloads/trackAff_feed.csv")

In [3]:
df_trackaff.head()

,date,operator_name,tracking_id,card_id,registrations,ftds,commission_per_ftd,total_commission,currency
0,03/31/2025,LuckyEdge,2.503313e+11,303,416.0,60.0,250,15000.0,GBP
1,03/31/2025,LuckyEdge,2.503313e+11,302,184.0,1.0,250,250.0,GBP
2,03/31/2025,LuckyEdge,2.503313e+11,301,937.0,13.0,250,3250.0,GBP
3,03/31/2025,SpinZone,2.503312e+11,203,162.0,42.0,175,7350.0,EUR
4,03/31/2025,SpinZone,2.503312e+11,202,867.0,89.0,175,15575.0,EUR

In [4]:
df_trackaff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                814 non-null    object
 1   operator_name       814 non-null    object
 2   tracking_id         811 non-null    float64
 3   card_id             814 non-null    int64
 4   registrations       812 non-null    float64
 5   ftds                812 non-null    float64
 6   commission_per_ftd  814 non-null    int64
 7   total_commission    812 non-null    float64
 8   currency            814 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 57.4+ KB

In [5]:
df_affmatrix.head()

,player_id,operator_name,product,tracking_id,card_id,registration_date,ftd_date,commission_per_ftd,commission_earned,currency
0,PLY0004058,StarStake,NaN,250331603003,603,31/03/2025,NaN,300,0,USD
1,PLY0004061,StarStake,NaN,250331603003,603,31/03/2025,NaN,300,0,USD
2,PLY0004056,StarStake,NaN,250331603003,603,31/03/2025,NaN,300,0,USD
3,PLY0004057,StarStake,NaN,250331603003,603,31/03/2025,NaN,300,0,USD
4,PLY0004059,StarStake,NaN,250331603003,603,31/03/2025,NaN,300,0,USD

In [6]:
df_affmatrix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4066 entries, 0 to 4065
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   player_id           4060 non-null   object
 1   operator_name       4066 non-null   object
 2   product             1373 non-null   object
 3   tracking_id         4066 non-null   int64
 4   card_id             4066 non-null   int64
 5   registration_date   4066 non-null   object
 6   ftd_date            2015 non-null   object
 7   commission_per_ftd  4066 non-null   int64
 8   commission_earned   4066 non-null   int64
 9   currency            4066 non-null   object
dtypes: int64(4), object(6)
memory usage: 317.8+ KB

In [7]:
df_campaign.head()

,date,campaign_id,campaign_name,impressions,clicks,inbounds,outbounds,spend_gbp,Unnamed: 8
0,31/03/2025,1,Spring_Slots_Push,83606,1597,1562,714,195.51,NaN
1,31/03/2025,2,Welcome_Bonus_Drive,44439,1596,1533,514,102.39,NaN
2,31/03/2025,3,Champions_Sports_Promo,54967,1361,1295,446,183.70,NaN
3,30/03/2025,1,Spring_Slots_Push,82442,1953,1923,1137,174.83,NaN
4,30/03/2025,2,Welcome_Bonus_Drive,63376,2388,2343,984,107.15,NaN

In [8]:
df_campaign.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           270 non-null    object
 1   campaign_id    270 non-null    int64
 2   campaign_name  270 non-null    object
 3   impressions    270 non-null    int64
 4   clicks         270 non-null    int64
 5   inbounds       270 non-null    int64
 6   outbounds      270 non-null    int64
 7   spend_gbp      270 non-null    float64
 8   Unnamed: 8     0 non-null      float64
dtypes: float64(2), int64(5), object(2)
memory usage: 19.1+ KB

#### Copy raw tables into working tables

In [9]:
trackaff_df2 = df_trackaff.copy()
affmatrix_df2 = df_affmatrix.copy()
campaign_df2 = df_campaign.copy()

In [10]:
trackaff_df2['date'].unique()

array(['03/31/2025', '03/30/2025', '03/29/2025', '03/28/2025',
       '03/27/2025', '03/26/2025', '03/25/2025', '03/24/2025',
       '03/23/2025', '03/22/2025', '03/21/2025', '03/20/2025',
       '03/19/2025', '03/18/2025', '03/17/2025', '03/16/2025',
       '03/15/2025', '03/14/2025', '03/13/2025', '03/12/2025',
       '03/11/2025', '03/10/2025', '03/09/2025', '03/08/2025',
       '03/07/2025', '03/06/2025', '03/05/2025', '03/04/2025',
       '03/03/2025', '03/02/2025', '03/01/2025', '28/02/2025',
       '27/02/2025', '26/02/2025', '25/02/2025', '24/02/2025',
       '23/02/2025', '22/02/2025', '21/02/2025', '20/02/2025',
       '19/02/2025', '18/02/2025', '17/02/2025', '16/02/2025',
       '15/02/2025', '14/02/2025', '13/02/2025', '12/02/2025',
       '11/02/2025', '10/02/2025', '09/02/2025', '08/02/2025',
       '07/02/2025', '06/02/2025', '05/02/2025', '04/02/2025',
       '02/02/2025', '01/02/2025', '31/01/2025', '30/01/2025',
       '29/01/2025', '28/01/2025', '27/01/2025', '26/01/2025',
       '25/01/2025', '24/01/2025', '23/01/2025', '22/01/2025',
       '21/01/2025', '20/01/2025', '19/01/2025', '18/01/2025',
       '17/01/2025', '16/01/2025', '15/01/2025', '14/01/2025',
       '13/01/2025', '12/01/2025', '11/01/2025', '10/01/2025',
       '09/01/2025', '08/01/2025', '07/01/2025', '06/01/2025',
       '05/01/2025', '04/01/2025', '02/01/2025', '01/01/2025'],
      dtype=object)

#### Standardize and Transform Date to: YYYY-MM-DD

In [11]:
trackaff_df2['date'] = pd.to_datetime(trackaff_df2["date"],format="mixed",dayfirst=True)

In [12]:
trackaff_df2['date'] = pd.to_datetime(trackaff_df2["date"],format="%d/%m/%Y",errors="coerce")

In [13]:
trackaff_df2['date']

0     2025-03-31
1     2025-03-31
2     2025-03-31
3     2025-03-31
4     2025-03-31
         ...
809   2025-01-01
810   2025-01-01
811   2025-02-10
812   2025-02-10
813   2025-02-11
Name: date, Length: 814, dtype: datetime64[ns]

In [14]:
affmatrix_df2["registration_date"] = pd.to_datetime(affmatrix_df2["registration_date"],errors="coerce")
affmatrix_df2["ftd_date"] = pd.to_datetime(affmatrix_df2["ftd_date"],errors="coerce")
campaign_df2["date"] = pd.to_datetime(campaign_df2["date"],errors="coerce")

C:\Users\OlusegunAdesanya\AppData\Local\Temp\ipykernel_35612\1197302289.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  affmatrix_df2["registration_date"] = pd.to_datetime(affmatrix_df2["registration_date"],errors="coerce")
C:\Users\OlusegunAdesanya\AppData\Local\Temp\ipykernel_35612\1197302289.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  affmatrix_df2["ftd_date"] = pd.to_datetime(affmatrix_df2["ftd_date"],errors="coerce")
C:\Users\OlusegunAdesanya\AppData\Local\Temp\ipykernel_35612\1197302289.py:3: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  campaign_df2["date"] = pd.to_datetime(campaign_df2["date"],errors="coerce")

#### Standardize tracking id column

In [29]:
trackaff_df2["tracking_id"] = trackaff_df2["tracking_id"].astype("Int64").astype(str)
..["tracking_id"] = affmatrix_df2["tracking_id"].astype("Int64").astype(str)

In [34]:
trackaff_df2["tracking_id"] = trackaff_df2["tracking_id"].str.replace("<NA>", "", regex=False).str.strip()
affmatrix_df2["tracking_id"] = affmatrix_df2["tracking_id"].str.replace("<NA>", "", regex=False).str.strip()

In [36]:
trackaff_df2["tracking_id"]

0      250331303003
1      250331302002
2      250331301001
3      250331203003
4      250331202002
           ...
809    250101102002
810    250101101001
811
812
813
Name: tracking_id, Length: 814, dtype: object

### Split tracking_id into date / card / campaign on  trackaff and affmatrix tables

Assume tracking_id as:

first 6 digits = YYMMDD

next 3 digits = card_id

last 3 digits = campaign_id

In [43]:
trackaff_df2["tracking_id_date"] = trackaff_df2["tracking_id"].str[:6]
trackaff_df2["tracking_id_card_id"] = trackaff_df2["tracking_id"].str[6:9]
trackaff_df2["tracking_id_campaign_id"] = trackaff_df2["tracking_id"].str[9:12]

affmatrix_df2["tracking_id_date"] = affmatrix_df2["tracking_id"].str[:6]
affmatrix_df2["tracking_id_card_id"] = affmatrix_df2["tracking_id"].str[6:9]
affmatrix_df2["tracking_id_campaign_id"] = affmatrix_df2["tracking_id"].str[9:12]

In [48]:
affmatrix_df2.tail()

,player_id,operator_name,product,tracking_id,card_id,registration_date,ftd_date,commission_per_ftd,commission_earned,currency,tracking_id_date,tracking_id_card_id,tracking_id_campaign_id
4061,PLY0000003,RoyalPlex,Casino,250101401001,401,2025-01-01,NaT,150,0,EUR,250101,401,001
4062,PLY0000004,RoyalPlex,Casino,250101401001,401,2025-01-01,2025-01-03,150,150,EUR,250101,401,001
4063,PLY0000006,RoyalPlex,Casino,250101401001,401,2025-01-01,2025-01-04,150,150,EUR,250101,401,001
4064,PLY0000005,RoyalPlex,Casino,250101401001,401,2025-01-01,2025-01-12,150,150,EUR,250101,401,001
4065,PLY0000002,RoyalPlex,Casino,250101401001,401,2025-01-01,2025-01-05,150,150,EUR,250101,401,001

In [49]:
trackaff_df2.tail()

,date,operator_name,tracking_id,card_id,registrations,ftds,commission_per_ftd,total_commission,currency,tracking_id_date,tracking_id_card_id,tracking_id_campaign_id
809,2025-01-01,NovaBet,250101102002,102,75.0,23.0,200,4600.0,GBP,250101,102,002
810,2025-01-01,NovaBet,250101101001,101,704.0,28.0,200,5600.0,GBP,250101,101,001
811,2025-02-10,NovaBet,,101,773.0,109.0,200,21800.0,GBP,,,
812,2025-02-10,LuckyEdge,,303,927.0,294.0,250,73500.0,GBP,,,
813,2025-02-11,SpinZone,,201,449.0,107.0,175,18725.0,EUR,,,

### Create column to map Currency to GBP

Assumed coversion rates:

GBP = 1.00

EUR = 0.86

USD = 0.79

In [53]:
fx_to_gbp = {
    "GBP": 1.00,
    "EUR": 0.86,
    "USD": 0.79
}

In [57]:
trackaff_df2["fx_to_gbp"] = trackaff_df2["currency"].map(fx_to_gbp)
affmatrix_df2["fx_to_gbp"] = affmatrix_df2["currency"].map(fx_to_gbp)

In [71]:
trackaff_df2["total_commission_gbp"] = trackaff_df2["total_commission"] * trackaff_df2["fx_to_gbp"]
trackaff_df2["commission_per_ftd_gbp"] = trackaff_df2["commission_per_ftd"] * trackaff_df2["fx_to_gbp"]

affmatrix_df2["commission_earned_gbp"] = affmatrix_df2["commission_earned"] * affmatrix_df2["fx_to_gbp"]
affmatrix_df2["commission_per_ftd_gbp"] = affmatrix_df2["commission_per_ftd"] * affmatrix_df2["fx_to_gbp"]

### Preview cleaned data

In [72]:
trackaff_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 814 entries, 0 to 813
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     814 non-null    datetime64[ns]
 1   operator_name            814 non-null    object
 2   tracking_id              814 non-null    object
 3   card_id                  814 non-null    int64
 4   registrations            812 non-null    float64
 5   ftds                     812 non-null    float64
 6   commission_per_ftd       814 non-null    int64
 7   total_commission         812 non-null    float64
 8   currency                 814 non-null    object
 9   tracking_id_date         814 non-null    object
 10  tracking_id_card_id      814 non-null    object
 11  tracking_id_campaign_id  814 non-null    object
 12  fx_to_gbp                814 non-null    float64
 13  total_commission_gbp     812 non-null    float64
 14  commission_per_ftd_gbp   814 non-null    float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(6)
memory usage: 95.5+ KB

In [73]:
affmatrix_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4066 entries, 0 to 4065
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   player_id                4060 non-null   object
 1   operator_name            4066 non-null   object
 2   product                  1373 non-null   object
 3   tracking_id              4066 non-null   object
 4   card_id                  4066 non-null   int64
 5   registration_date        4066 non-null   datetime64[ns]
 6   ftd_date                 2015 non-null   datetime64[ns]
 7   commission_per_ftd       4066 non-null   int64
 8   commission_earned        4066 non-null   int64
 9   currency                 4066 non-null   object
 10  tracking_id_date         4066 non-null   object
 11  tracking_id_card_id      4066 non-null   object
 12  tracking_id_campaign_id  4066 non-null   object
 13  fx_to_gbp                4066 non-null   float64
 14  commission_earned_gbp    4066 non-null   float64
 15  commission_per_ftd_gbp   4066 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(8)
memory usage: 508.4+ KB

### Export preprocessed tables

In [74]:
trackaff_df2.to_csv("trackAff_feed_clean.csv", index=False)
affmatrix_df2.to_csv("affMatrix_feed_clean.csv", index=False)
campaign_df2.to_csv("campaign_data_clean.csv", index=False)